name: inter_intel_interview
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  animations: ^2.0.2
  bloc: ^7.2.0
  cupertino_icons: ^1.0.3
  curved_navigation_bar: ^1.0.1
  dio: ^4.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_localizations:
    sdk: flutter
  formz: ^0.4.1
  get: ^4.3.8
  intl: ^0.17.0
  rounded_loading_button: ^2.0.9

dev_dependencies:
  bloc_test: ^8.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
